title: Workshop on Serverless Data Analytics
subtitle: 1 September 2023 - Vancouver, Canada
logo: "images/vancouver.jpg?raw=true"
description: 1 September 2023 - Vancouver, Canada (co-located with VLDB 2023 Conference)
theme: jekyll-theme-minimal
