title: Workshop on Serverless Data Analytics
subtitle: 1 September 2023 - Vancouver, Canada
description: 1 September 2023 - Vancouver, Canada (co-located with VLDB 2023 Conference)
theme: jekyll-theme-minimal
